# Generated by Django 6.0.3 on 2026-06-24 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _migrate_ticket_routes(apps, schema_editor):
    Route = apps.get_model('api', 'Route')
    Ticket = apps.get_model('api', 'Ticket')

    for ticket in Ticket.objects.all():
        route_value = ticket.route
        if not route_value:
            continue
        if isinstance(route_value, int):
            route_obj = Route.objects.filter(id=route_value).first()
        else:
            route_obj = Route.objects.filter(origin=route_value).first()
            if not route_obj and isinstance(route_value, str):
                normalized = route_value.strip()
                route_obj = Route.objects.filter(origin__iexact=normalized).first()
                if not route_obj:
                    route_obj = Route.objects.filter(origin__iexact=normalized.split(' - ')[0]).first()
        if route_obj:
            ticket.route_id = route_obj.id
            ticket.save(update_fields=['route'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PUVType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='iwp_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='province',
            field=models.CharField(default='La Union', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mode',
            field=models.CharField(choices=[('UNLOAD', 'Unload'), ('QUEUE', 'Queue')], default='QUEUE', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='franchise_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operator_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _migrate_ticket_routes(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='api.route'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transportation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='api.puvtype'),
        ),
        migrations.CreateModel(
            name='RemittanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='remittance_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='api.remittancebatch'),
        ),
    ]
