# Generated by Django 6.0.3 on 2026-06-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_denomination_puvtype_driver_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
