# Generated by Django 6.0.3 on 2026-06-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='code',
        ),
    ]
