# Generated by Django 6.0.3 on 2026-06-26 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remittancebatch_collection_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remittancebatch',
            name='collection_amount',
        ),
        migrations.RemoveField(
            model_name='remittancebatch',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='remittancebatch',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='remittancebatch',
            name='from_no',
        ),
        migrations.RemoveField(
            model_name='remittancebatch',
            name='ticket_form_no',
        ),
        migrations.RemoveField(
            model_name='remittancebatch',
            name='to_no',
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_form_no', models.CharField(blank=True, max_length=50, null=True)),
                ('from_no', models.CharField(blank=True, max_length=20, null=True)),
                ('to_no', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='api.remittancebatch')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bill', 'Bill'), ('coin', 'Coin')], max_length=10)),
                ('denomination', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='api.remittancebatch')),
            ],
        ),
    ]
