# Generated by Django 6.0.6 on 2026-06-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_remittancebatch_collection_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='denomination',
            name='type',
            field=models.CharField(choices=[('bill', 'Bill'), ('coin', 'Coin')], default='bill', max_length=10),
        ),
    ]
