# Generated by Django 6.0.6 on 2026-06-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_requisition_ticketseries_ticket_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketseries',
            name='denomination',
        ),
        migrations.AddField(
            model_name='ticketseries',
            name='ticket_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ticketform'),
        ),
    ]
