# Generated by Django 6.0.6 on 2026-06-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_ticketseries_denomination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketform',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
