# Generated by Django 6.0.6 on 2026-09-13 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_vehicle_owner_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CSV', 'CSV Import'), ('REMOTE', 'Remote Request')], max_length=10)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('issued_at', models.DateTimeField()),
                ('csv_filename', models.CharField(blank=True, default='', max_length=255)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='backfill_csv/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backfill_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
