# Generated by Django 6.0.6 on 2026-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_backfillrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backfillrecord',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
