# Generated by Django 6.0.6 on 2026-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_backfillrecord_issued_at_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='estimated_loading_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='loading_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
